#!/bin/bash
# Script for uninstall robot tools

# ----- FX Team -----

#

# Coded by: YOUSEFABBAS-dew

#  * https://github.com/v7y3/

# Feel free to share any ideas with the
# project!
#
# -------------------------

clear

echo "

";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then

    INSTALL_DIR="$PREFIX/usr/share/doc/robot"

    BIN_DIR="$PREFIX/bin/"

    BASH_PATH="$PREFIX/bin/bash"

    TERMUX=true

elif [ "$(uname)" = "Darwin" ]; then

    INSTALL_DIR="/usr/local/robot"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

else

    INSTALL_DIR="$HOME/.robot"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

fi

echo "[✔] Checking directories...";

if [ -d "$INSTALL_DIR" ]; then

        rm -rf "$INSTALL_DIR"

        rm "$BIN_DIR/robot*"

        sudo rm -rf "$INSTALL_DIR"

        sudo rm "$BIN_DIR/robot*"

    else

        echo "[✘] If you want to uninstall you must remove previous installations [✘] ";

        echo "[✘] Failed! [✘] ";

fi

echo "[✔] Cleaning up old directories...";

if [ -d "$ETC_DIR/Manisso" ]; then

    echo "$DIR_FOUND_TEXT"

    if [ "$TERMUX" = true ]; then

        rm -rf "$ETC_DIR/Manisso"

    else

        sudo rm -rf "$ETC_DIR/Manisso"

    fi

fi

clear

clear

echo "[✔] all good!"
